# Generated by Django 2.1.5 on 2019-04-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
