# Generated by Django 2.1.5 on 2019-04-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_personalinfo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
