# Generated by Django 2.1.5 on 2019-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20190412_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
