# Generated by Django 2.1.5 on 2019-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_personalinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
